import { useState } from 'react';
import { LayoutGrid, Cpu, Play, Layers } from 'lucide-react';

interface WorkspaceItem {
  id: string;
  name: string;
  description: string;
  status: 'ACTIVE' | 'STANDBY' | 'LOCKED';
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
  signalCount: number;
  lastActivity: string;
}

export function Workspaces() {
  const [workspaces] = useState<WorkspaceItem[]>([
    {
      id: 'ws-omega',
      name: 'Omega Ops',
      description: 'Live operational dashboard generated by NEXUS. Ingests fleet logs, calculates payroll leaks, and manages clearances.',
      status: 'ACTIVE',
      riskLevel: 'LOW',
      signalCount: 12,
      lastActivity: '3m ago'
    },
    {
      id: 'ws-recruit',
      name: 'Recruitment Hub',
      description: 'Secure AI screening product generated by NEXUS. Handles CV parsing, private storage routing, and verification.',
      status: 'STANDBY',
      riskLevel: 'MEDIUM',
      signalCount: 4,
      lastActivity: '1h ago'
    },
    {
      id: 'ws-powershield',
      name: 'PowerShield',
      description: 'Advanced local security proxy generated by NEXUS. Supervises Bridge Daemons and monitors API traffic for leaks.',
      status: 'ACTIVE',
      riskLevel: 'HIGH',
      signalCount: 27,
      lastActivity: 'Just now'
    }
  ]);

  const [deploymentLogs, setDeploymentLogs] = useState<string[]>([
    'INIT: Workspace engine initialized.',
    'READY: Templates catalog synced (3 systems loaded).'
  ]);
  const [launchState, setLaunchState] = useState<Record<string, string>>({});

  const deployWorkspace = async (id: string, name: string) => {
    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
    setDeploymentLogs(prev => [...prev, `[${time}] DEPLOY: Initiating workspace launch for ${name}...`]);

    if (id === 'ws-powershield') {
      setDeploymentLogs(prev => [...prev, `[${time}] FAIL: Product not yet compiled for standalone execution.`]);
      return;
    }

    const serviceMap: Record<string, { service: string, port: number }> = {
      'ws-omega': { service: 'omega-dashboard', port: 3000 },
      'ws-recruit': { service: 'recruitment-hub', port: 5174 }
    };

    const target = serviceMap[id];
    if (!target) return;

    try {
      setLaunchState(prev => ({ ...prev, [id]: 'Launching...' }));
      // Check status
      let res = await fetch('/api/services/status');
      let data = await res.json();
      let isOnline = data.connections?.some((c: any) => c.LocalPort === target.port);

      if (!isOnline) {
        setDeploymentLogs(prev => [...prev, `[${time}] SYS: Service offline. Triggering background launch sequence...`]);
        await fetch('/api/services/action', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ service: target.service, action: 'launch' })
        });
        
        // Wait and poll
        for (let i = 0; i < 15; i++) {
          await new Promise(resolve => setTimeout(resolve, 1000));
          res = await fetch('/api/services/status');
          data = await res.json();
          isOnline = data.connections?.some((c: any) => c.LocalPort === target.port);
          if (isOnline) break;
        }
      }

      if (isOnline) {
        setLaunchState(prev => ({ ...prev, [id]: 'Opening...' }));
        setDeploymentLogs(prev => [...prev, `[${time}] SUCCESS: Service active on port ${target.port}. Launching app window...`]);
        const openRes = await fetch('/api/services/action', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ service: target.service, action: 'open' })
        });
        
        if (!openRes.ok) throw new Error(`HTTP ${openRes.status}`);
        const openData = await openRes.json();
        
        if (openData.ok) {
          setLaunchState(prev => ({ ...prev, [id]: 'Opened' }));
          setTimeout(() => { setLaunchState(prev => ({ ...prev, [id]: '' })); }, 5000);
        } else {
          throw new Error(openData.error || 'Failed to open window');
        }
      } else {
        throw new Error('Service failed to start within timeout window.');
      }

    } catch (e: any) {
      console.error(e);
      setLaunchState(prev => ({ ...prev, [id]: `Failed: ${e.message}` }));
      setDeploymentLogs(prev => [...prev, `[${time}] ERROR: ${e.message}`]);
      setTimeout(() => { setLaunchState(prev => ({ ...prev, [id]: '' })); }, 5000);
    }
  };

  return (
    <section className="nova-center-core" style={{
      gridColumn: 'center / span 2',
      background: 'rgba(3, 8, 16, 0.45)',
      border: '1px solid var(--border)',
      borderRadius: 'var(--radius)',
      padding: '20px',
      display: 'grid',
      gridTemplateColumns: '1.2fr 0.8fr',
      gap: '16px',
      height: '100%',
      overflow: 'hidden'
    }}>
      {/* Left Column: Active Systems */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', height: '100%', overflowY: 'auto', paddingRight: '4px' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
          <div className="compartment-label">[BAY-03 DEPLOYMENT GRID]</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginTop: '2px' }}>
            <LayoutGrid size={16} style={{ color: 'var(--cyan)' }} />
            <h2 style={{ color: 'var(--text-bright)', fontSize: '0.8rem', letterSpacing: '1px', fontWeight: 800, textTransform: 'uppercase', fontFamily: 'var(--mono)', margin: 0 }}>
              Active Operational Workspaces
            </h2>
          </div>
        </div>

        {/* Workspace Cards */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          {workspaces.map((ws) => (
            <div key={ws.id} className="glass" style={{
              padding: '12px',
              display: 'flex',
              flexDirection: 'column',
              gap: '8px',
              background: 'rgba(5, 12, 24, 0.4)'
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.52rem', fontWeight: 800, color: 'var(--text-bright)', fontFamily: 'var(--mono)' }}>
                  {ws.name}
                </span>
                <span style={{
                  fontSize: '0.38rem',
                  fontFamily: 'var(--mono)',
                  fontWeight: 700,
                  padding: '2px 6px',
                  borderRadius: '3px',
                  background: ws.status === 'ACTIVE' ? 'rgba(0, 230, 118, 0.15)' : 'rgba(255, 171, 0, 0.15)',
                  color: ws.status === 'ACTIVE' ? 'var(--green)' : 'var(--amber)',
                  border: ws.status === 'ACTIVE' ? '1px solid rgba(0,230,118,0.2)' : '1px solid rgba(255,171,0,0.2)'
                }}>
                  {ws.status}
                </span>
              </div>

              <p style={{ fontSize: '0.46rem', color: 'var(--text-main)', margin: 0, lineHeight: 1.4 }}>
                {ws.description}
              </p>

              {/* Telemetry Stats */}
              <div style={{
                display: 'flex',
                gap: '12px',
                fontSize: '0.4rem',
                fontFamily: 'var(--mono)',
                color: 'var(--text-muted)',
                borderTop: '1px solid rgba(255,255,255,0.03)',
                paddingTop: '6px',
                marginTop: '4px'
              }}>
                <span>RISK: <strong style={{ color: ws.riskLevel === 'HIGH' ? 'var(--red)' : ws.riskLevel === 'MEDIUM' ? 'var(--amber)' : 'var(--green)' }}>{ws.riskLevel}</strong></span>
                <span>•</span>
                <span>SIGNALS: <strong style={{ color: 'var(--cyan)' }}>{ws.signalCount}</strong></span>
                <span>•</span>
                <span>ACTIVITY: <strong style={{ color: 'var(--text-bright)' }}>{ws.lastActivity}</strong></span>
              </div>

              {/* Load/Launch Button */}
              <div style={{ display: 'flex', gap: '8px', marginTop: '4px' }}>
                <button 
                  onClick={() => deployWorkspace(ws.id, ws.name)}
                  disabled={ws.id === 'ws-powershield' || !!launchState[ws.id]}
                  style={{
                    background: ws.id === 'ws-powershield' ? 'rgba(255,255,255,0.05)' : 'rgba(0, 210, 255, 0.08)',
                    border: ws.id === 'ws-powershield' ? '1px solid rgba(255,255,255,0.1)' : '1px solid rgba(0, 210, 255, 0.2)',
                    color: ws.id === 'ws-powershield' ? 'var(--text-muted)' : launchState[ws.id]?.includes('Failed') ? 'var(--red)' : launchState[ws.id] === 'Opened' ? 'var(--green)' : 'var(--cyan)',
                    fontSize: '0.42rem',
                    fontWeight: 600,
                    padding: '4px 10px',
                    borderRadius: '3px',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '4px',
                    cursor: ws.id === 'ws-powershield' || !!launchState[ws.id] ? 'not-allowed' : 'pointer'
                  }}
                >
                  <Play size={10} /> {ws.id === 'ws-powershield' ? 'COMING SOON' : launchState[ws.id] || 'LAUNCH PRODUCT'}
                </button>
              </div>
            </div>
          ))}
        </div>

        {/* Active Deployment Diagnostics Console (Eliminating empty void at bottom of workspaces list) */}
        <div className="glass" style={{
          padding: '12px',
          background: 'rgba(0, 0, 0, 0.4)',
          border: '1px solid rgba(0, 210, 255, 0.15)',
          borderRadius: '4px',
          display: 'flex',
          flexDirection: 'column',
          gap: '6px',
          marginTop: '10px'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid rgba(255,255,255,0.03)', paddingBottom: '4px' }}>
            <span style={{ fontSize: '0.4rem', fontFamily: 'var(--mono)', color: 'var(--cyan)', fontWeight: 800 }}>
              &gt; WORKSPACE COMPARTMENT DIAGNOSTIC SCANNER
            </span>
            <span style={{ fontSize: '0.36rem', fontFamily: 'var(--mono)', color: 'var(--green)' }}>SYS_INTEGRITY: OK</span>
          </div>
          <div className="hex-dump-matrix" style={{ maxHeight: '72px', overflowY: 'hidden', opacity: 0.8 }}>
            0x00FF8C  -  [SYS] OMEGA SECURE PORT 3000 SYNCED SUCCESSFULLY (DB CLEARANCE: LEVEL 5){"\n"}
            0x00FF9D  -  [SYS] RECRUITMENT ISOLATED SANDBOX MOUNTED ON /omega-cvs{"\n"}
            0x00FFAE  -  [SYS] TELEGRAM DAEMON ACTIVE (RTT CHECK: NOMINAL 12ms)
          </div>
        </div>
      </div>

      {/* Right Column: Deployment Deck Terminal */}
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        borderLeft: '1px solid var(--border)',
        paddingLeft: '16px',
        height: '100%',
        overflow: 'hidden'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          <Cpu size={14} style={{ color: 'var(--purple)' }} />
          <span style={{ fontSize: '0.48rem', fontWeight: 800, color: 'var(--text-bright)', letterSpacing: '0.5px', fontFamily: 'var(--mono)' }}>
            WORKSPACE CONSOLE
          </span>
        </div>

        {/* Logs terminal */}
        <div style={{
          flex: 1,
          background: 'rgba(0, 0, 0, 0.3)',
          border: '1px solid rgba(255, 255, 255, 0.03)',
          borderRadius: '4px',
          padding: '10px',
          fontFamily: 'var(--mono)',
          fontSize: '0.44rem',
          color: 'var(--text-bright)',
          overflowY: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: '6px'
        }}>
          {deploymentLogs.map((log, idx) => (
            <div key={idx} style={{
              color: log.includes('SUCCESS') ? 'var(--green)' : log.includes('DEPLOY') ? 'var(--cyan)' : '#8cb3db',
              lineHeight: 1.4
            }}>
              {log}
            </div>
          ))}
        </div>

        {/* Quick Instructions */}
        <div className="glass" style={{ padding: '10px', display: 'flex', flexDirection: 'column', gap: '6px', background: 'rgba(213,0,249,0.01)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.42rem', color: 'var(--purple)', fontWeight: 700 }}>
            <Layers size={10} />
            <span>OPERATIONAL TIP</span>
          </div>
          <p style={{ fontSize: '0.44rem', color: 'var(--text-main)', margin: 0, lineHeight: 1.4 }}>
            Workspaces partition database rules and local advisor memory. Selecting a workspace optimizes LLM ingestion matrices.
          </p>
        </div>
      </div>
    </section>
  );
}
